import argparse                                                                                                                                                                                                     
import json                                                                                                                                                                                                         
import numpy as np                                                                                                                                                                                                  
from collections import Counter                                                                                                                                                                                     
from pathlib import Path                    
                                                                                                                                                                                                                    
import chromadb                                                                                                                                                                                                     
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def get_collection():                                                                                                                                                                                               
    client = chromadb.PersistentClient(path="data/chromadb")                                                                                                                                                        
    return client.get_collection("integrable_systems")                                                                                                                                                              
                                            
                                                                                                                                                                                                                    
def cluster_chunks(collection, n_clusters=10):                                                                                                                                                                      
    """Simple k-means clustering on stored embeddings."""                                                                                                                                                           
    # Pull everything from ChromaDB                                                                                                                                                                                 
    results = collection.get(include=["embeddings", "metadatas", "documents"])                                                                                                                                      
                                                                                                                                                                                                                    
    ids = results["ids"]                                                                                                                                                                                            
    embeddings = np.array(results["embeddings"])                                                                                                                                                                    
    metadatas = results["metadatas"]                                                                                                                                                                                
    documents = results["documents"]                                                                                                                                                                                
                                                                                                                                                                                                                    
    print(f"Clustering {len(ids)} chunks into {n_clusters} groups...\n")                                                                                                                                            
                                                                                                                                                                                                                    
    # K-means (manual — avoids sklearn dependency on 8GB machine)                                                                                                                                                   
    labels = kmeans(embeddings, n_clusters, max_iter=50)                                                                                                                                                            
                                            
    # Analyze each cluster                                                                                                                                                                                          
    clusters = []                       
    for cluster_id in range(n_clusters):                                                                                                                                                                            
        mask = [i for i, label in enumerate(labels) if label == cluster_id]                                                                                                                                         
        if not mask:                                                                                                                                                                                                
            continue                                                                                                                                                                                                
                                                                                                                                                                                                                    
        cluster_metadatas = [metadatas[i] for i in mask]                                                                                                                                                            
        cluster_documents = [documents[i] for i in mask]                                                                                                                                                            
                                                                                                                                                                                                                    
        # Most common papers in this cluster                                                                                                                                                                        
        paper_titles = Counter(                                                                                                                                                                                     
            m["title"] for m in cluster_metadatas if m.get("title")                                                                                                                                                 
        )                                                                                                                                                                                                           
        top_papers = paper_titles.most_common(5)                                                                                                                                                                    
                                                                                                                                                                                                                    
        # Most common section names                                                                                                                                                                                 
        section_names = Counter(                                                                                                                                                                                    
            m["section"] for m in cluster_metadatas if m.get("section")                                                                                                                                             
        )                               
        top_sections = section_names.most_common(5)                                                                                                                                                                 
                                                                                                                                                                                                                    
        # Most common chunk types           
        chunk_types = Counter(                                                                                                                                                                                      
            m["chunk_type"] for m in cluster_metadatas if m.get("chunk_type")                                                                                                                                       
        )                                                                                                                                                                                                           
                                                                                                                                                                                                                    
        # Extract key terms from content (simple frequency approach)                                                                                                                                                
        key_terms = extract_key_terms(cluster_documents)                                                                                                                                                            
                                                                                                                                                                                                                    
        cluster_info = {                                                                                                                                                                                            
            "cluster_id": cluster_id,                                                                                                                                                                               
            "size": len(mask),                                                                                                                                                                                      
            "top_papers": top_papers,                                                                                                                                                                               
            "top_sections": top_sections,                                                                                                                                                                           
            "chunk_types": chunk_types.most_common(),                                                                                                                                                               
            "key_terms": key_terms,                                                                                                                                                                                 
            "sample_snippet": cluster_documents[0][:300] if cluster_documents else "",                                                                                                                              
        }                                                                                                                                                                                                           
        clusters.append(cluster_info)                                                                                                                                                                               
                                                                                                                                                                                                                    
    # Sort by size descending                                                                                                                                                                                       
    clusters.sort(key=lambda c: c["size"], reverse=True)                                                                                                                                                            
    return clusters                                                                                                                                                                                                 
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def kmeans(data, k, max_iter=50):                                                                                                                                                                                   
    """Minimal k-means implementation to avoid extra dependencies."""
    n = len(data)                                                                                                                                                                                                   
    rng = np.random.default_rng(42)         
                                                                                                                                                                                                                    
    # Initialize centroids with k-means++                                                                                                                                                                           
    centroids = [data[rng.integers(n)]]                                                                                                                                                                             
    for _ in range(1, k):                                                                                                                                                                                           
        distances = np.array([                                                                                                                                                                                      
            min(np.linalg.norm(point - c) for c in centroids)                                                                                                                                                       
            for point in data                                                                                                                                                                                       
        ])                                                                                                                                                                                                          
        probabilities = distances ** 2                                                                                                                                                                              
        probabilities /= probabilities.sum()                                                                                                                                                                        
        next_idx = rng.choice(n, p=probabilities)                                                                                                                                                                   
        centroids.append(data[next_idx])                                                                                                                                                                            
    centroids = np.array(centroids)                                                                                                                                                                                 
                                                                                                                                                                                                                    
    labels = np.zeros(n, dtype=int)                                                                                                                                                                                 
                                                                                                                                                                                                                    
    for iteration in range(max_iter):                                                                                                                                                                               
        # Assign each point to nearest centroid                                                                                                                                                                     
        new_labels = np.array([                                                                                                                                                                                     
            np.argmin([np.linalg.norm(point - c) for c in centroids])                                                                                                                                               
            for point in data               
        ])                                                                                                                                                                                                          
                                                                                                                                                                                                                    
        # Check convergence                                                                                                                                                                                         
        if np.array_equal(new_labels, labels):                                                                                                                                                                      
            print(f"  Converged at iteration {iteration + 1}")                                                                                                                                                      
            break                                                                                                                                                                                                   
        labels = new_labels                 
                                                                                                                                                                                                                    
        # Update centroids                                                                                                                                                                                          
        for j in range(k):                                                                                                                                                                                          
            members = data[labels == j]                                                                                                                                                                             
            if len(members) > 0:                                                                                                                                                                                    
                centroids[j] = members.mean(axis=0)                                                                                                                                                                 
                                                                                                                                                                                                                    
    return labels                                                                                                                                                                                                   
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def extract_key_terms(documents, top_n=10):                                                                                                                                                                         
    """Extract frequent math-relevant terms from chunk texts."""                                                                                                                                                    
    # Terms that signal mathematical topics                                                                                                                                                                         
    math_terms = [                          
        "Calogero", "Moser", "Ruijsenaars", "Schneider", "Lax",                                                                                                                                                     
        "Hamiltonian", "integrable", "elliptic", "rational", "trigonometric",                                                                                                                                       
        "hyperbolic", "spin", "quantum", "classical", "r-matrix",                                                                                                                                                   
        "Hitchin", "spectral curve", "Dunkl", "operator", "many-body",                                                                                                                                              
        "symplectic", "Poisson", "bracket", "commuting", "hierarchy",                                                                                                                                               
        "KP", "KdV", "soliton", "scattering", "inverse",                                                                                                                                                            
        "affine", "root system", "Weyl", "Coxeter", "reflection",                                                                                                                                                   
        "gauge", "bundle", "moduli", "connection", "flat",                                                                                                                                                          
        "representation", "algebra", "Yangian", "Knizhnik", "Zamolodchikov",                                                                                                                                        
        "dynamical", "Yang-Baxter", "partition function", "determinant",                                                                                                                                            
        "eigenvalue", "polynomial", "Jack", "Macdonald", "Heckman",                                                                                                                                                 
        "Opdam", "Cherednik", "DAHA", "deformation", "quantization",                                                                                                                                                
    ]                                                                                                                                                                                                               
                                                                                                                                                                                                                    
    all_text = " ".join(documents).lower()                                                                                                                                                                          
    counts = {}                                                                                                                                                                                                     
    for term in math_terms:                                                                                                                                                                                         
        count = all_text.count(term.lower())                                                                                                                                                                        
        if count > 0:                                                                                                                                                                                               
            counts[term] = count                                                                                                                                                                                    
                                                                                                                                                                                                                    
    sorted_terms = sorted(counts.items(), key=lambda x: x[1], reverse=True)                                                                                                                                         
    return sorted_terms[:top_n]                                                                                                                                                                                     
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def display_clusters(clusters):                                                                                                                                                                                     
    """Print cluster analysis in a readable format."""                                                                                                                                                              
    print("=" * 60)                                                                                                                                                                                                 
    print("TOPIC CLUSTERS")                                                                                                                                                                                         
    print("=" * 60)                                                                                                                                                                                                 
                                                                                                                                                                                                                    
    for cluster in clusters:                                                                                                                                                                                        
        print(f"\n--- Cluster {cluster['cluster_id']} ({cluster['size']} chunks) ---")                                                                                                                              
                                                                                                                                                                                                                    
        print("  Key terms:")                                                                                                                                                                                       
        for term, count in cluster["key_terms"]:                                                                                                                                                                    
            print(f"    {term}: {count}")                                                                                                                                                                           
                                                                                                                                                                                                                    
        print("  Top papers:")                                                                                                                                                                                      
        for title, count in cluster["top_papers"]:                                                                                                                                                                  
            short_title = title[:70] if title else "(untitled)"                                                                                                                                                     
            print(f"    [{count}] {short_title}")                                                                                                                                                                   
                                                                                                                                                                                                                    
        print("  Common sections:")                                                                                                                                                                                 
        for section, count in cluster["top_sections"][:3]:                                                                                                                                                          
            print(f"    [{count}] {section}")                                                                                                                                                                       
                                                                                                                                                                                                                    
        print(f"  Sample: {cluster['sample_snippet'][:150]}...")                                                                                                                                                    
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def suggest_review_topics(clusters):                                                                                                                                                                                
    """Suggest potential review paper topics based on clusters."""                                                                                                                                                  
    print("\n" + "=" * 60)                                                                                                                                                                                          
    print("SUGGESTED REVIEW TOPICS")        
    print("=" * 60)                                                                                                                                                                                                 
                                                                                                                                                                                                                    
    suggestions = []                                                                                                                                                                                                
    for cluster in clusters:                                                                                                                                                                                        
        terms = [term for term, _ in cluster["key_terms"][:5]]                                                                                                                                                      
        if len(terms) >= 2:                                                                                                                                                                                         
            suggestion = " + ".join(terms[:3])                                                                                                                                                                      
            suggestions.append((suggestion, cluster["size"]))                                                                                                                                                       
                                                                                                                                                                                                                    
    for i, (topic, size) in enumerate(suggestions, 1):                                                                                                                                                              
        print(f"  {i}. {topic} ({size} chunks)")                                                                                                                                                                    
                                                                                                                                                                                                                    
    print("\nPick a topic number or describe your own focus.")                                                                                                                                                      
    print("This will guide the retrieval in the generation step.")                                                                                                                                                  
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def main():                                                                                                                                                                                                         
    parser = argparse.ArgumentParser(                                                                                                                                                                               
        description="Discover topics in the embedded corpus"
    )                                                                                                                                                                                                               
    parser.add_argument(                
        "--clusters", type=int, default=10,                                                                                                                                                                         
        help="Number of clusters (default: 10)",                                                                                                                                                                    
    )                                                                                                                                                                                                               
    args = parser.parse_args()                                                                                                                                                                                      
                                                                                                                                                                                                                    
    collection = get_collection()                                                                                                                                                                                   
                                                                                                                                                                                                                    
    if collection.count() == 0:                                                                                                                                                                                     
        print("No embeddings found. Run 03_embed_store.py first.")                                                                                                                                                  
        return                                                                                                                                                                                                      
                                                                                                                                                                                                                    
    clusters = cluster_chunks(collection, n_clusters=args.clusters)
    display_clusters(clusters)                                                                                                                                                                                      
    suggest_review_topics(clusters)                                                                                                                                                                                 
                                                                                                                                                                                                                    
    # Save for reference                                                                                                                                                                                            
    output_path = Path("data/topic_clusters.json")                                                                                                                                                                  
    serializable = []                                                                                                                                                                                               
    for cluster in clusters:                                                                                                                                                                                        
        cluster_copy = dict(cluster)                                                                                                                                                                                
        cluster_copy["chunk_types"] = dict(cluster_copy["chunk_types"])                                                                                                                                             
        serializable.append(cluster_copy)                                                                                                                                                                           
                                                                                                                                                                                                                    
    with open(output_path, "w") as f:                                                                                                                                                                               
        json.dump(serializable, f, indent=2, ensure_ascii=False)                                                                                                                                                    
    print(f"\nSaved to {output_path}")                                                                                                                                                                              
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
if __name__ == "__main__":                                                                                                                                                                                          
    main()